<?php

namespace AppBundle\Repository;

/**
 * AstronauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AstronauteRepository extends \Doctrine\ORM\EntityRepository
{
}
